### PR TITLE
Feature/test product pierre2

### PR DESCRIPTION
**Pull request by Klurifixus**

### CODE REVIEW

**Comment by Klurifixus** [comment]
#53 uppdaterat årtal i footern

**Comment by BornTheWrongAnimal** [comment]
Changes in footer ok

**Comment by BornTheWrongAnimal** [comment]
Changes in footer OK

**Review by BornTheWrongAnimal — COMMENTED** [review]
ok

**Review by BornTheWrongAnimal — APPROVED** [review]

**Pull request merged**
